// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth_api.dart';
import 'api/book_api.dart';
import 'api/borrowing_api.dart';
import 'api/camera_api.dart';
import 'api/face_api.dart';
import 'api/penalty_api.dart';
import 'api/report_api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/book.dart';
import 'domain/borrowing.dart';
import 'domain/penalty.dart';
import 'domain/report.dart';
import 'domain/user.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2010143214;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_librarymanagementsystem',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiBookApiAddBook({
    required String title,
    required String author,
    required int publicationYear,
    required String isbn,
    required String genre,
    required int copies,
    String? imageUrl,
    required double fineFee,
    required int maxBorrowDays,
  });

  Future<void> crateApiBorrowingApiApproveBorrowing({
    required String borrowingId,
    required String dueDate,
  });

  Future<void> crateApiBorrowingApiBorrowBook({
    required String userId,
    required String userName,
    required String bookId,
    required int borrowDays,
  });

  Future<Uint8List> crateApiCameraApiCaptureFrame();

  Future<void> crateApiBookApiDeleteBook({required String id});

  Future<LibraryReport> crateApiReportApiGenerateReport();

  Future<List<Book>> crateApiBookApiGetAllBooks({
    required int limit,
    required int offset,
  });

  Future<List<Borrowing>> crateApiBorrowingApiGetAllBorrowings();

  Future<List<Penalty>> crateApiPenaltyApiGetAllPenalties();

  Future<List<User>> crateApiAuthApiGetAllUsers();

  Future<List<Borrowing>> crateApiBorrowingApiGetPendingBorrowings();

  Future<List<Borrowing>> crateApiBorrowingApiGetUserBorrowings({
    required String userId,
  });

  Future<User> crateApiAuthApiGetUserById({required String id});

  Future<List<Penalty>> crateApiPenaltyApiGetUserPenalties({
    required String userId,
  });

  Future<void> crateApiInitApp();

  Future<void> crateApiCameraApiInitCamera();

  Future<User> crateApiAuthApiLoginUser({
    required String identifier,
    required String passwordPlain,
  });

  Future<void> crateApiPenaltyApiPayPenalty({required String penaltyId});

  Future<void> crateApiBorrowingApiProcessReturn({
    required String borrowingId,
    required bool isApproved,
    String? conditionNotes,
    double? feeAmount,
  });

  Future<void> crateApiFaceApiRegisterFace({
    required String userId,
    required List<int> imageBytes,
  });

  Future<String> crateApiAuthApiRegisterUser({
    required String username,
    required String passwordPlain,
    required String fullName,
    required String role,
    required String securityQuestion,
    required String securityAnswer,
  });

  Future<void> crateApiBorrowingApiRejectBorrowing({
    required String borrowingId,
  });

  Future<void> crateApiBorrowingApiRequestReturn({required String borrowingId});

  Future<void> crateApiAuthApiResetPassword({
    required String username,
    required String securityAnswer,
    required String newPasswordPlain,
  });

  Future<List<Book>> crateApiBookApiSearchBooks({required String query});

  Future<void> crateApiBorrowingApiSendReminder({required String borrowingId});

  Future<void> crateApiCameraApiStopCamera();

  Future<void> crateApiBookApiUpdateBook({required Book book});

  Future<void> crateApiAuthApiUpdateUser({required User user});

  Future<String?> crateApiFaceApiVerifyFace({required List<int> imageBytes});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiBookApiAddBook({
    required String title,
    required String author,
    required int publicationYear,
    required String isbn,
    required String genre,
    required int copies,
    String? imageUrl,
    required double fineFee,
    required int maxBorrowDays,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(author, serializer);
          sse_encode_i_32(publicationYear, serializer);
          sse_encode_String(isbn, serializer);
          sse_encode_String(genre, serializer);
          sse_encode_i_32(copies, serializer);
          sse_encode_opt_String(imageUrl, serializer);
          sse_encode_f_64(fineFee, serializer);
          sse_encode_i_32(maxBorrowDays, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBookApiAddBookConstMeta,
        argValues: [
          title,
          author,
          publicationYear,
          isbn,
          genre,
          copies,
          imageUrl,
          fineFee,
          maxBorrowDays,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookApiAddBookConstMeta => const TaskConstMeta(
    debugName: "add_book",
    argNames: [
      "title",
      "author",
      "publicationYear",
      "isbn",
      "genre",
      "copies",
      "imageUrl",
      "fineFee",
      "maxBorrowDays",
    ],
  );

  @override
  Future<void> crateApiBorrowingApiApproveBorrowing({
    required String borrowingId,
    required String dueDate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(borrowingId, serializer);
          sse_encode_String(dueDate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiApproveBorrowingConstMeta,
        argValues: [borrowingId, dueDate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiApproveBorrowingConstMeta =>
      const TaskConstMeta(
        debugName: "approve_borrowing",
        argNames: ["borrowingId", "dueDate"],
      );

  @override
  Future<void> crateApiBorrowingApiBorrowBook({
    required String userId,
    required String userName,
    required String bookId,
    required int borrowDays,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(userName, serializer);
          sse_encode_String(bookId, serializer);
          sse_encode_i_32(borrowDays, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiBorrowBookConstMeta,
        argValues: [userId, userName, bookId, borrowDays],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiBorrowBookConstMeta =>
      const TaskConstMeta(
        debugName: "borrow_book",
        argNames: ["userId", "userName", "bookId", "borrowDays"],
      );

  @override
  Future<Uint8List> crateApiCameraApiCaptureFrame() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraApiCaptureFrameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraApiCaptureFrameConstMeta =>
      const TaskConstMeta(debugName: "capture_frame", argNames: []);

  @override
  Future<void> crateApiBookApiDeleteBook({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBookApiDeleteBookConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookApiDeleteBookConstMeta =>
      const TaskConstMeta(debugName: "delete_book", argNames: ["id"]);

  @override
  Future<LibraryReport> crateApiReportApiGenerateReport() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReportApiGenerateReportConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReportApiGenerateReportConstMeta =>
      const TaskConstMeta(debugName: "generate_report", argNames: []);

  @override
  Future<List<Book>> crateApiBookApiGetAllBooks({
    required int limit,
    required int offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(limit, serializer);
          sse_encode_i_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_book,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBookApiGetAllBooksConstMeta,
        argValues: [limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookApiGetAllBooksConstMeta => const TaskConstMeta(
    debugName: "get_all_books",
    argNames: ["limit", "offset"],
  );

  @override
  Future<List<Borrowing>> crateApiBorrowingApiGetAllBorrowings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_borrowing,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiGetAllBorrowingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiGetAllBorrowingsConstMeta =>
      const TaskConstMeta(debugName: "get_all_borrowings", argNames: []);

  @override
  Future<List<Penalty>> crateApiPenaltyApiGetAllPenalties() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_penalty,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPenaltyApiGetAllPenaltiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPenaltyApiGetAllPenaltiesConstMeta =>
      const TaskConstMeta(debugName: "get_all_penalties", argNames: []);

  @override
  Future<List<User>> crateApiAuthApiGetAllUsers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_user,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthApiGetAllUsersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthApiGetAllUsersConstMeta =>
      const TaskConstMeta(debugName: "get_all_users", argNames: []);

  @override
  Future<List<Borrowing>> crateApiBorrowingApiGetPendingBorrowings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_borrowing,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiGetPendingBorrowingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiGetPendingBorrowingsConstMeta =>
      const TaskConstMeta(debugName: "get_pending_borrowings", argNames: []);

  @override
  Future<List<Borrowing>> crateApiBorrowingApiGetUserBorrowings({
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_borrowing,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiGetUserBorrowingsConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiGetUserBorrowingsConstMeta =>
      const TaskConstMeta(
        debugName: "get_user_borrowings",
        argNames: ["userId"],
      );

  @override
  Future<User> crateApiAuthApiGetUserById({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthApiGetUserByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthApiGetUserByIdConstMeta =>
      const TaskConstMeta(debugName: "get_user_by_id", argNames: ["id"]);

  @override
  Future<List<Penalty>> crateApiPenaltyApiGetUserPenalties({
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_penalty,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPenaltyApiGetUserPenaltiesConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPenaltyApiGetUserPenaltiesConstMeta =>
      const TaskConstMeta(
        debugName: "get_user_penalties",
        argNames: ["userId"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiCameraApiInitCamera() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraApiInitCameraConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraApiInitCameraConstMeta =>
      const TaskConstMeta(debugName: "init_camera", argNames: []);

  @override
  Future<User> crateApiAuthApiLoginUser({
    required String identifier,
    required String passwordPlain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(identifier, serializer);
          sse_encode_String(passwordPlain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthApiLoginUserConstMeta,
        argValues: [identifier, passwordPlain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthApiLoginUserConstMeta => const TaskConstMeta(
    debugName: "login_user",
    argNames: ["identifier", "passwordPlain"],
  );

  @override
  Future<void> crateApiPenaltyApiPayPenalty({required String penaltyId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(penaltyId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPenaltyApiPayPenaltyConstMeta,
        argValues: [penaltyId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPenaltyApiPayPenaltyConstMeta =>
      const TaskConstMeta(debugName: "pay_penalty", argNames: ["penaltyId"]);

  @override
  Future<void> crateApiBorrowingApiProcessReturn({
    required String borrowingId,
    required bool isApproved,
    String? conditionNotes,
    double? feeAmount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(borrowingId, serializer);
          sse_encode_bool(isApproved, serializer);
          sse_encode_opt_String(conditionNotes, serializer);
          sse_encode_opt_box_autoadd_f_64(feeAmount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiProcessReturnConstMeta,
        argValues: [borrowingId, isApproved, conditionNotes, feeAmount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiProcessReturnConstMeta =>
      const TaskConstMeta(
        debugName: "process_return",
        argNames: ["borrowingId", "isApproved", "conditionNotes", "feeAmount"],
      );

  @override
  Future<void> crateApiFaceApiRegisterFace({
    required String userId,
    required List<int> imageBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFaceApiRegisterFaceConstMeta,
        argValues: [userId, imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFaceApiRegisterFaceConstMeta =>
      const TaskConstMeta(
        debugName: "register_face",
        argNames: ["userId", "imageBytes"],
      );

  @override
  Future<String> crateApiAuthApiRegisterUser({
    required String username,
    required String passwordPlain,
    required String fullName,
    required String role,
    required String securityQuestion,
    required String securityAnswer,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(passwordPlain, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_String(role, serializer);
          sse_encode_String(securityQuestion, serializer);
          sse_encode_String(securityAnswer, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthApiRegisterUserConstMeta,
        argValues: [
          username,
          passwordPlain,
          fullName,
          role,
          securityQuestion,
          securityAnswer,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthApiRegisterUserConstMeta =>
      const TaskConstMeta(
        debugName: "register_user",
        argNames: [
          "username",
          "passwordPlain",
          "fullName",
          "role",
          "securityQuestion",
          "securityAnswer",
        ],
      );

  @override
  Future<void> crateApiBorrowingApiRejectBorrowing({
    required String borrowingId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(borrowingId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiRejectBorrowingConstMeta,
        argValues: [borrowingId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiRejectBorrowingConstMeta =>
      const TaskConstMeta(
        debugName: "reject_borrowing",
        argNames: ["borrowingId"],
      );

  @override
  Future<void> crateApiBorrowingApiRequestReturn({
    required String borrowingId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(borrowingId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiRequestReturnConstMeta,
        argValues: [borrowingId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiRequestReturnConstMeta =>
      const TaskConstMeta(
        debugName: "request_return",
        argNames: ["borrowingId"],
      );

  @override
  Future<void> crateApiAuthApiResetPassword({
    required String username,
    required String securityAnswer,
    required String newPasswordPlain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(securityAnswer, serializer);
          sse_encode_String(newPasswordPlain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthApiResetPasswordConstMeta,
        argValues: [username, securityAnswer, newPasswordPlain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthApiResetPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "reset_password",
        argNames: ["username", "securityAnswer", "newPasswordPlain"],
      );

  @override
  Future<List<Book>> crateApiBookApiSearchBooks({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_book,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBookApiSearchBooksConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookApiSearchBooksConstMeta =>
      const TaskConstMeta(debugName: "search_books", argNames: ["query"]);

  @override
  Future<void> crateApiBorrowingApiSendReminder({required String borrowingId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(borrowingId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBorrowingApiSendReminderConstMeta,
        argValues: [borrowingId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBorrowingApiSendReminderConstMeta =>
      const TaskConstMeta(
        debugName: "send_reminder",
        argNames: ["borrowingId"],
      );

  @override
  Future<void> crateApiCameraApiStopCamera() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraApiStopCameraConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraApiStopCameraConstMeta =>
      const TaskConstMeta(debugName: "stop_camera", argNames: []);

  @override
  Future<void> crateApiBookApiUpdateBook({required Book book}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_book(book, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBookApiUpdateBookConstMeta,
        argValues: [book],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookApiUpdateBookConstMeta =>
      const TaskConstMeta(debugName: "update_book", argNames: ["book"]);

  @override
  Future<void> crateApiAuthApiUpdateUser({required User user}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_user(user, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthApiUpdateUserConstMeta,
        argValues: [user],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthApiUpdateUserConstMeta =>
      const TaskConstMeta(debugName: "update_user", argNames: ["user"]);

  @override
  Future<String?> crateApiFaceApiVerifyFace({required List<int> imageBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFaceApiVerifyFaceConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFaceApiVerifyFaceConstMeta =>
      const TaskConstMeta(debugName: "verify_face", argNames: ["imageBytes"]);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  Map<String, int> dco_decode_Map_String_i_32_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_i_32(raw).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActiveBorrower dco_decode_active_borrower(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ActiveBorrower(
      userId: dco_decode_String(arr[0]),
      borrowerName: dco_decode_String(arr[1]),
      bookTitle: dco_decode_String(arr[2]),
      borrowDate: dco_decode_String(arr[3]),
      dueDate: dco_decode_String(arr[4]),
    );
  }

  @protected
  Book dco_decode_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return Book(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      author: dco_decode_String(arr[2]),
      publicationYear: dco_decode_i_32(arr[3]),
      isbn: dco_decode_String(arr[4]),
      genre: dco_decode_String(arr[5]),
      copies: dco_decode_i_32(arr[6]),
      isAvailable: dco_decode_bool(arr[7]),
      imageUrl: dco_decode_opt_String(arr[8]),
      fineFee: dco_decode_f_64(arr[9]),
      maxBorrowDays: dco_decode_i_32(arr[10]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BorrowStatus dco_decode_borrow_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BorrowStatus.values[raw as int];
  }

  @protected
  Borrowing dco_decode_borrowing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return Borrowing(
      id: dco_decode_String(arr[0]),
      bookId: dco_decode_String(arr[1]),
      userId: dco_decode_String(arr[2]),
      borrowerName: dco_decode_String(arr[3]),
      borrowDate: dco_decode_Chrono_Utc(arr[4]),
      dueDate: dco_decode_Chrono_Utc(arr[5]),
      returnDate: dco_decode_opt_box_autoadd_Chrono_Utc(arr[6]),
      isReturned: dco_decode_bool(arr[7]),
      status: dco_decode_borrow_status(arr[8]),
      hasReminder: dco_decode_bool(arr[9]),
      returnStatus: dco_decode_return_status(arr[10]),
      conditionNotes: dco_decode_opt_String(arr[11]),
      bookTitle: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Chrono_Utc(raw);
  }

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_book(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  User dco_decode_box_autoadd_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_user(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LibraryReport dco_decode_library_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return LibraryReport(
      totalBooks: dco_decode_i_32(arr[0]),
      availableBooks: dco_decode_i_32(arr[1]),
      borrowedBooks: dco_decode_i_32(arr[2]),
      totalUsers: dco_decode_i_32(arr[3]),
      genreDistribution: dco_decode_Map_String_i_32_None(arr[4]),
      mostlyBorrowedGenre: dco_decode_String(arr[5]),
      borrowedBooksList: dco_decode_list_book(arr[6]),
      activeBorrowers: dco_decode_list_active_borrower(arr[7]),
    );
  }

  @protected
  List<ActiveBorrower> dco_decode_list_active_borrower(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_active_borrower).toList();
  }

  @protected
  List<Book> dco_decode_list_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book).toList();
  }

  @protected
  List<Borrowing> dco_decode_list_borrowing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_borrowing).toList();
  }

  @protected
  List<Penalty> dco_decode_list_penalty(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_penalty).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, int)> dco_decode_list_record_string_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_i_32).toList();
  }

  @protected
  List<User> dco_decode_list_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_user).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  Penalty dco_decode_penalty(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Penalty(
      id: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      borrowingId: dco_decode_opt_String(arr[2]),
      amount: dco_decode_f_64(arr[3]),
      reason: dco_decode_String(arr[4]),
      isPaid: dco_decode_bool(arr[5]),
      createdAt: dco_decode_Chrono_Utc(arr[6]),
    );
  }

  @protected
  (String, int) dco_decode_record_string_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_i_32(arr[1]));
  }

  @protected
  ReturnStatus dco_decode_return_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReturnStatus.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  User dco_decode_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return User(
      id: dco_decode_String(arr[0]),
      username: dco_decode_String(arr[1]),
      passwordHash: dco_decode_String(arr[2]),
      fullName: dco_decode_String(arr[3]),
      role: dco_decode_user_role(arr[4]),
      contactDetails: dco_decode_opt_String(arr[5]),
      securityQuestion: dco_decode_String(arr[6]),
      securityAnswer: dco_decode_String(arr[7]),
    );
  }

  @protected
  UserRole dco_decode_user_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UserRole.values[raw as int];
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  Map<String, int> sse_decode_Map_String_i_32_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_i_32(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActiveBorrower sse_decode_active_borrower(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_borrowerName = sse_decode_String(deserializer);
    var var_bookTitle = sse_decode_String(deserializer);
    var var_borrowDate = sse_decode_String(deserializer);
    var var_dueDate = sse_decode_String(deserializer);
    return ActiveBorrower(
      userId: var_userId,
      borrowerName: var_borrowerName,
      bookTitle: var_bookTitle,
      borrowDate: var_borrowDate,
      dueDate: var_dueDate,
    );
  }

  @protected
  Book sse_decode_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_publicationYear = sse_decode_i_32(deserializer);
    var var_isbn = sse_decode_String(deserializer);
    var var_genre = sse_decode_String(deserializer);
    var var_copies = sse_decode_i_32(deserializer);
    var var_isAvailable = sse_decode_bool(deserializer);
    var var_imageUrl = sse_decode_opt_String(deserializer);
    var var_fineFee = sse_decode_f_64(deserializer);
    var var_maxBorrowDays = sse_decode_i_32(deserializer);
    return Book(
      id: var_id,
      title: var_title,
      author: var_author,
      publicationYear: var_publicationYear,
      isbn: var_isbn,
      genre: var_genre,
      copies: var_copies,
      isAvailable: var_isAvailable,
      imageUrl: var_imageUrl,
      fineFee: var_fineFee,
      maxBorrowDays: var_maxBorrowDays,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BorrowStatus sse_decode_borrow_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BorrowStatus.values[inner];
  }

  @protected
  Borrowing sse_decode_borrowing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_bookId = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_borrowerName = sse_decode_String(deserializer);
    var var_borrowDate = sse_decode_Chrono_Utc(deserializer);
    var var_dueDate = sse_decode_Chrono_Utc(deserializer);
    var var_returnDate = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_isReturned = sse_decode_bool(deserializer);
    var var_status = sse_decode_borrow_status(deserializer);
    var var_hasReminder = sse_decode_bool(deserializer);
    var var_returnStatus = sse_decode_return_status(deserializer);
    var var_conditionNotes = sse_decode_opt_String(deserializer);
    var var_bookTitle = sse_decode_opt_String(deserializer);
    return Borrowing(
      id: var_id,
      bookId: var_bookId,
      userId: var_userId,
      borrowerName: var_borrowerName,
      borrowDate: var_borrowDate,
      dueDate: var_dueDate,
      returnDate: var_returnDate,
      isReturned: var_isReturned,
      status: var_status,
      hasReminder: var_hasReminder,
      returnStatus: var_returnStatus,
      conditionNotes: var_conditionNotes,
      bookTitle: var_bookTitle,
    );
  }

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Chrono_Utc(deserializer));
  }

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_book(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  User sse_decode_box_autoadd_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_user(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LibraryReport sse_decode_library_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalBooks = sse_decode_i_32(deserializer);
    var var_availableBooks = sse_decode_i_32(deserializer);
    var var_borrowedBooks = sse_decode_i_32(deserializer);
    var var_totalUsers = sse_decode_i_32(deserializer);
    var var_genreDistribution = sse_decode_Map_String_i_32_None(deserializer);
    var var_mostlyBorrowedGenre = sse_decode_String(deserializer);
    var var_borrowedBooksList = sse_decode_list_book(deserializer);
    var var_activeBorrowers = sse_decode_list_active_borrower(deserializer);
    return LibraryReport(
      totalBooks: var_totalBooks,
      availableBooks: var_availableBooks,
      borrowedBooks: var_borrowedBooks,
      totalUsers: var_totalUsers,
      genreDistribution: var_genreDistribution,
      mostlyBorrowedGenre: var_mostlyBorrowedGenre,
      borrowedBooksList: var_borrowedBooksList,
      activeBorrowers: var_activeBorrowers,
    );
  }

  @protected
  List<ActiveBorrower> sse_decode_list_active_borrower(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ActiveBorrower>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_active_borrower(deserializer));
    }
    return ans_;
  }

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Book>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book(deserializer));
    }
    return ans_;
  }

  @protected
  List<Borrowing> sse_decode_list_borrowing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Borrowing>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_borrowing(deserializer));
    }
    return ans_;
  }

  @protected
  List<Penalty> sse_decode_list_penalty(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Penalty>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_penalty(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, int)> sse_decode_list_record_string_i_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, int)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_i_32(deserializer));
    }
    return ans_;
  }

  @protected
  List<User> sse_decode_list_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <User>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_user(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Chrono_Utc(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Penalty sse_decode_penalty(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_borrowingId = sse_decode_opt_String(deserializer);
    var var_amount = sse_decode_f_64(deserializer);
    var var_reason = sse_decode_String(deserializer);
    var var_isPaid = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    return Penalty(
      id: var_id,
      userId: var_userId,
      borrowingId: var_borrowingId,
      amount: var_amount,
      reason: var_reason,
      isPaid: var_isPaid,
      createdAt: var_createdAt,
    );
  }

  @protected
  (String, int) sse_decode_record_string_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_i_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ReturnStatus sse_decode_return_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReturnStatus.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  User sse_decode_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_passwordHash = sse_decode_String(deserializer);
    var var_fullName = sse_decode_String(deserializer);
    var var_role = sse_decode_user_role(deserializer);
    var var_contactDetails = sse_decode_opt_String(deserializer);
    var var_securityQuestion = sse_decode_String(deserializer);
    var var_securityAnswer = sse_decode_String(deserializer);
    return User(
      id: var_id,
      username: var_username,
      passwordHash: var_passwordHash,
      fullName: var_fullName,
      role: var_role,
      contactDetails: var_contactDetails,
      securityQuestion: var_securityQuestion,
      securityAnswer: var_securityAnswer,
    );
  }

  @protected
  UserRole sse_decode_user_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UserRole.values[inner];
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_i_32_None(
    Map<String, int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_i_32(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_active_borrower(
    ActiveBorrower self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.borrowerName, serializer);
    sse_encode_String(self.bookTitle, serializer);
    sse_encode_String(self.borrowDate, serializer);
    sse_encode_String(self.dueDate, serializer);
  }

  @protected
  void sse_encode_book(Book self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_i_32(self.publicationYear, serializer);
    sse_encode_String(self.isbn, serializer);
    sse_encode_String(self.genre, serializer);
    sse_encode_i_32(self.copies, serializer);
    sse_encode_bool(self.isAvailable, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_f_64(self.fineFee, serializer);
    sse_encode_i_32(self.maxBorrowDays, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_borrow_status(BorrowStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_borrowing(Borrowing self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.bookId, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.borrowerName, serializer);
    sse_encode_Chrono_Utc(self.borrowDate, serializer);
    sse_encode_Chrono_Utc(self.dueDate, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.returnDate, serializer);
    sse_encode_bool(self.isReturned, serializer);
    sse_encode_borrow_status(self.status, serializer);
    sse_encode_bool(self.hasReminder, serializer);
    sse_encode_return_status(self.returnStatus, serializer);
    sse_encode_opt_String(self.conditionNotes, serializer);
    sse_encode_opt_String(self.bookTitle, serializer);
  }

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Chrono_Utc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_book(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_user(User self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_library_report(LibraryReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.totalBooks, serializer);
    sse_encode_i_32(self.availableBooks, serializer);
    sse_encode_i_32(self.borrowedBooks, serializer);
    sse_encode_i_32(self.totalUsers, serializer);
    sse_encode_Map_String_i_32_None(self.genreDistribution, serializer);
    sse_encode_String(self.mostlyBorrowedGenre, serializer);
    sse_encode_list_book(self.borrowedBooksList, serializer);
    sse_encode_list_active_borrower(self.activeBorrowers, serializer);
  }

  @protected
  void sse_encode_list_active_borrower(
    List<ActiveBorrower> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_active_borrower(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book(item, serializer);
    }
  }

  @protected
  void sse_encode_list_borrowing(
    List<Borrowing> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_borrowing(item, serializer);
    }
  }

  @protected
  void sse_encode_list_penalty(List<Penalty> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_penalty(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_i_32(
    List<(String, int)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_i_32(item, serializer);
    }
  }

  @protected
  void sse_encode_list_user(List<User> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_user(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Chrono_Utc(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_penalty(Penalty self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_opt_String(self.borrowingId, serializer);
    sse_encode_f_64(self.amount, serializer);
    sse_encode_String(self.reason, serializer);
    sse_encode_bool(self.isPaid, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
  }

  @protected
  void sse_encode_record_string_i_32(
    (String, int) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_i_32(self.$2, serializer);
  }

  @protected
  void sse_encode_return_status(ReturnStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user(User self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.passwordHash, serializer);
    sse_encode_String(self.fullName, serializer);
    sse_encode_user_role(self.role, serializer);
    sse_encode_opt_String(self.contactDetails, serializer);
    sse_encode_String(self.securityQuestion, serializer);
    sse_encode_String(self.securityAnswer, serializer);
  }

  @protected
  void sse_encode_user_role(UserRole self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
