// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth_api.dart';
import 'api/book_api.dart';
import 'api/borrowing_api.dart';
import 'api/camera_api.dart';
import 'api/face_api.dart';
import 'api/penalty_api.dart';
import 'api/report_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain/book.dart';
import 'domain/borrowing.dart';
import 'domain/penalty.dart';
import 'domain/report.dart';
import 'domain/user.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  Map<String, int> dco_decode_Map_String_i_32_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveBorrower dco_decode_active_borrower(dynamic raw);

  @protected
  Book dco_decode_book(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BorrowStatus dco_decode_borrow_status(dynamic raw);

  @protected
  Borrowing dco_decode_borrowing(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  User dco_decode_box_autoadd_user(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibraryReport dco_decode_library_report(dynamic raw);

  @protected
  List<ActiveBorrower> dco_decode_list_active_borrower(dynamic raw);

  @protected
  List<Book> dco_decode_list_book(dynamic raw);

  @protected
  List<Borrowing> dco_decode_list_borrowing(dynamic raw);

  @protected
  List<Penalty> dco_decode_list_penalty(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, int)> dco_decode_list_record_string_i_32(dynamic raw);

  @protected
  List<User> dco_decode_list_user(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  Penalty dco_decode_penalty(dynamic raw);

  @protected
  (String, int) dco_decode_record_string_i_32(dynamic raw);

  @protected
  ReturnStatus dco_decode_return_status(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  User dco_decode_user(dynamic raw);

  @protected
  UserRole dco_decode_user_role(dynamic raw);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Map<String, int> sse_decode_Map_String_i_32_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveBorrower sse_decode_active_borrower(SseDeserializer deserializer);

  @protected
  Book sse_decode_book(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BorrowStatus sse_decode_borrow_status(SseDeserializer deserializer);

  @protected
  Borrowing sse_decode_borrowing(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  User sse_decode_box_autoadd_user(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibraryReport sse_decode_library_report(SseDeserializer deserializer);

  @protected
  List<ActiveBorrower> sse_decode_list_active_borrower(
    SseDeserializer deserializer,
  );

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer);

  @protected
  List<Borrowing> sse_decode_list_borrowing(SseDeserializer deserializer);

  @protected
  List<Penalty> sse_decode_list_penalty(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, int)> sse_decode_list_record_string_i_32(
    SseDeserializer deserializer,
  );

  @protected
  List<User> sse_decode_list_user(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  Penalty sse_decode_penalty(SseDeserializer deserializer);

  @protected
  (String, int) sse_decode_record_string_i_32(SseDeserializer deserializer);

  @protected
  ReturnStatus sse_decode_return_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  User sse_decode_user(SseDeserializer deserializer);

  @protected
  UserRole sse_decode_user_role(SseDeserializer deserializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_i_32_None(
    Map<String, int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_borrower(
    ActiveBorrower self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_borrow_status(BorrowStatus self, SseSerializer serializer);

  @protected
  void sse_encode_borrowing(Borrowing self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library_report(LibraryReport self, SseSerializer serializer);

  @protected
  void sse_encode_list_active_borrower(
    List<ActiveBorrower> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer);

  @protected
  void sse_encode_list_borrowing(
    List<Borrowing> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_penalty(List<Penalty> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_i_32(
    List<(String, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user(List<User> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_penalty(Penalty self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_i_32(
    (String, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_return_status(ReturnStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_user_role(UserRole self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
