// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Book {
  final String id;
  final String title;
  final String author;
  final int publicationYear;
  final String isbn;
  final String genre;
  final bool isAvailable;

  const Book({
    required this.id,
    required this.title,
    required this.author,
    required this.publicationYear,
    required this.isbn,
    required this.genre,
    required this.isAvailable,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      publicationYear.hashCode ^
      isbn.hashCode ^
      genre.hashCode ^
      isAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Book &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          publicationYear == other.publicationYear &&
          isbn == other.isbn &&
          genre == other.genre &&
          isAvailable == other.isAvailable;
}

class Borrowing {
  final String id;
  final String bookId;
  final String userId;
  final String borrowerName;
  final DateTime borrowDate;
  final DateTime? returnDate;
  final bool isReturned;

  const Borrowing({
    required this.id,
    required this.bookId,
    required this.userId,
    required this.borrowerName,
    required this.borrowDate,
    this.returnDate,
    required this.isReturned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      userId.hashCode ^
      borrowerName.hashCode ^
      borrowDate.hashCode ^
      returnDate.hashCode ^
      isReturned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Borrowing &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          userId == other.userId &&
          borrowerName == other.borrowerName &&
          borrowDate == other.borrowDate &&
          returnDate == other.returnDate &&
          isReturned == other.isReturned;
}

class LibraryReport {
  final int totalBooks;
  final int availableBooks;
  final int borrowedBooks;
  final int totalUsers;
  final Map<String, int> genreDistribution;

  const LibraryReport({
    required this.totalBooks,
    required this.availableBooks,
    required this.borrowedBooks,
    required this.totalUsers,
    required this.genreDistribution,
  });

  @override
  int get hashCode =>
      totalBooks.hashCode ^
      availableBooks.hashCode ^
      borrowedBooks.hashCode ^
      totalUsers.hashCode ^
      genreDistribution.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryReport &&
          runtimeType == other.runtimeType &&
          totalBooks == other.totalBooks &&
          availableBooks == other.availableBooks &&
          borrowedBooks == other.borrowedBooks &&
          totalUsers == other.totalUsers &&
          genreDistribution == other.genreDistribution;
}

class User {
  final String id;
  final String username;
  final String passwordHash;
  final String fullName;
  final UserRole role;
  final String? contactDetails;
  final String securityQuestion;
  final String securityAnswer;

  const User({
    required this.id,
    required this.username,
    required this.passwordHash,
    required this.fullName,
    required this.role,
    this.contactDetails,
    required this.securityQuestion,
    required this.securityAnswer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      username.hashCode ^
      passwordHash.hashCode ^
      fullName.hashCode ^
      role.hashCode ^
      contactDetails.hashCode ^
      securityQuestion.hashCode ^
      securityAnswer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username &&
          passwordHash == other.passwordHash &&
          fullName == other.fullName &&
          role == other.role &&
          contactDetails == other.contactDetails &&
          securityQuestion == other.securityQuestion &&
          securityAnswer == other.securityAnswer;
}

enum UserRole { student, librarian }
