// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Book {
  final String id;
  final String title;
  final String author;
  final int publicationYear;
  final String isbn;
  final String genre;
  final int copies;
  final bool isAvailable;
  final String? imageUrl;
  final double fineFee;
  final int maxBorrowDays;

  const Book({
    required this.id,
    required this.title,
    required this.author,
    required this.publicationYear,
    required this.isbn,
    required this.genre,
    required this.copies,
    required this.isAvailable,
    this.imageUrl,
    required this.fineFee,
    required this.maxBorrowDays,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      publicationYear.hashCode ^
      isbn.hashCode ^
      genre.hashCode ^
      copies.hashCode ^
      isAvailable.hashCode ^
      imageUrl.hashCode ^
      fineFee.hashCode ^
      maxBorrowDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Book &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          publicationYear == other.publicationYear &&
          isbn == other.isbn &&
          genre == other.genre &&
          copies == other.copies &&
          isAvailable == other.isAvailable &&
          imageUrl == other.imageUrl &&
          fineFee == other.fineFee &&
          maxBorrowDays == other.maxBorrowDays;
}
