// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum BorrowStatus { pending, approved, rejected }

class Borrowing {
  final String id;
  final String bookId;
  final String userId;
  final String borrowerName;
  final DateTime borrowDate;
  final DateTime dueDate;
  final DateTime? returnDate;
  final bool isReturned;
  final BorrowStatus status;
  final bool hasReminder;
  final ReturnStatus returnStatus;
  final String? conditionNotes;
  final String? bookTitle;
  final String? bookIsbn;

  const Borrowing({
    required this.id,
    required this.bookId,
    required this.userId,
    required this.borrowerName,
    required this.borrowDate,
    required this.dueDate,
    this.returnDate,
    required this.isReturned,
    required this.status,
    required this.hasReminder,
    required this.returnStatus,
    this.conditionNotes,
    this.bookTitle,
    this.bookIsbn,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      userId.hashCode ^
      borrowerName.hashCode ^
      borrowDate.hashCode ^
      dueDate.hashCode ^
      returnDate.hashCode ^
      isReturned.hashCode ^
      status.hashCode ^
      hasReminder.hashCode ^
      returnStatus.hashCode ^
      conditionNotes.hashCode ^
      bookTitle.hashCode ^
      bookIsbn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Borrowing &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          userId == other.userId &&
          borrowerName == other.borrowerName &&
          borrowDate == other.borrowDate &&
          dueDate == other.dueDate &&
          returnDate == other.returnDate &&
          isReturned == other.isReturned &&
          status == other.status &&
          hasReminder == other.hasReminder &&
          returnStatus == other.returnStatus &&
          conditionNotes == other.conditionNotes &&
          bookTitle == other.bookTitle &&
          bookIsbn == other.bookIsbn;
}

enum ReturnStatus { none, pending, approved, rejected }
