// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Penalty {
  final String id;
  final String userId;
  final String? borrowingId;
  final double amount;
  final String reason;
  final bool isPaid;
  final DateTime createdAt;

  const Penalty({
    required this.id,
    required this.userId,
    this.borrowingId,
    required this.amount,
    required this.reason,
    required this.isPaid,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      borrowingId.hashCode ^
      amount.hashCode ^
      reason.hashCode ^
      isPaid.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Penalty &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          borrowingId == other.borrowingId &&
          amount == other.amount &&
          reason == other.reason &&
          isPaid == other.isPaid &&
          createdAt == other.createdAt;
}
