// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ActiveBorrower {
  final String userId;
  final String borrowerName;
  final String bookTitle;
  final String borrowDate;
  final String dueDate;

  const ActiveBorrower({
    required this.userId,
    required this.borrowerName,
    required this.bookTitle,
    required this.borrowDate,
    required this.dueDate,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      borrowerName.hashCode ^
      bookTitle.hashCode ^
      borrowDate.hashCode ^
      dueDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveBorrower &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          borrowerName == other.borrowerName &&
          bookTitle == other.bookTitle &&
          borrowDate == other.borrowDate &&
          dueDate == other.dueDate;
}

class LibraryReport {
  final int totalBooks;
  final int availableBooks;
  final int borrowedBooks;
  final int totalUsers;
  final Map<String, int> genreDistribution;
  final String mostlyBorrowedGenre;
  final List<Book> borrowedBooksList;
  final List<ActiveBorrower> activeBorrowers;

  const LibraryReport({
    required this.totalBooks,
    required this.availableBooks,
    required this.borrowedBooks,
    required this.totalUsers,
    required this.genreDistribution,
    required this.mostlyBorrowedGenre,
    required this.borrowedBooksList,
    required this.activeBorrowers,
  });

  @override
  int get hashCode =>
      totalBooks.hashCode ^
      availableBooks.hashCode ^
      borrowedBooks.hashCode ^
      totalUsers.hashCode ^
      genreDistribution.hashCode ^
      mostlyBorrowedGenre.hashCode ^
      borrowedBooksList.hashCode ^
      activeBorrowers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryReport &&
          runtimeType == other.runtimeType &&
          totalBooks == other.totalBooks &&
          availableBooks == other.availableBooks &&
          borrowedBooks == other.borrowedBooks &&
          totalUsers == other.totalUsers &&
          genreDistribution == other.genreDistribution &&
          mostlyBorrowedGenre == other.mostlyBorrowedGenre &&
          borrowedBooksList == other.borrowedBooksList &&
          activeBorrowers == other.activeBorrowers;
}
