// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class User {
  final String id;
  final String username;
  final String passwordHash;
  final String fullName;
  final UserRole role;
  final String? contactDetails;
  final String securityQuestion;
  final String securityAnswer;

  const User({
    required this.id,
    required this.username,
    required this.passwordHash,
    required this.fullName,
    required this.role,
    this.contactDetails,
    required this.securityQuestion,
    required this.securityAnswer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      username.hashCode ^
      passwordHash.hashCode ^
      fullName.hashCode ^
      role.hashCode ^
      contactDetails.hashCode ^
      securityQuestion.hashCode ^
      securityAnswer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username &&
          passwordHash == other.passwordHash &&
          fullName == other.fullName &&
          role == other.role &&
          contactDetails == other.contactDetails &&
          securityQuestion == other.securityQuestion &&
          securityAnswer == other.securityAnswer;
}

enum UserRole { student, librarian }
