// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/user.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Registers a new user in the system.
Future<String> registerUser({
  required String username,
  required String passwordPlain,
  required String fullName,
  required String role,
  required String securityQuestion,
  required String securityAnswer,
}) => RustLib.instance.api.crateApiAuthApiRegisterUser(
  username: username,
  passwordPlain: passwordPlain,
  fullName: fullName,
  role: role,
  securityQuestion: securityQuestion,
  securityAnswer: securityAnswer,
);

/// Authenticates a user and returns their profile information.
Future<User> loginUser({
  required String identifier,
  required String passwordPlain,
}) => RustLib.instance.api.crateApiAuthApiLoginUser(
  identifier: identifier,
  passwordPlain: passwordPlain,
);

/// Updates an existing user's profile information.
Future<void> updateUser({required User user}) =>
    RustLib.instance.api.crateApiAuthApiUpdateUser(user: user);

/// Retrieves all registered users in the system.
Future<List<User>> getAllUsers() =>
    RustLib.instance.api.crateApiAuthApiGetAllUsers();

/// Resets a user's password if the security answer is correct.
Future<void> resetPassword({
  required String username,
  required String securityAnswer,
  required String newPasswordPlain,
}) => RustLib.instance.api.crateApiAuthApiResetPassword(
  username: username,
  securityAnswer: securityAnswer,
  newPasswordPlain: newPasswordPlain,
);

/// Retrieves a user by their ID.
Future<User> getUserById({required String id}) =>
    RustLib.instance.api.crateApiAuthApiGetUserById(id: id);
