// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/book.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Adds a new book to the library catalog.
Future<void> addBook({
  required String title,
  required String author,
  required int publicationYear,
  required String isbn,
  required String genre,
  required int copies,
  String? imageUrl,
  required double fineFee,
  required int maxBorrowDays,
}) => RustLib.instance.api.crateApiBookApiAddBook(
  title: title,
  author: author,
  publicationYear: publicationYear,
  isbn: isbn,
  genre: genre,
  copies: copies,
  imageUrl: imageUrl,
  fineFee: fineFee,
  maxBorrowDays: maxBorrowDays,
);

/// Retrieves a paginated list of books in the library.
Future<List<Book>> getAllBooks({required int limit, required int offset}) =>
    RustLib.instance.api.crateApiBookApiGetAllBooks(
      limit: limit,
      offset: offset,
    );

/// Searches for books matching the given title, author, or ISBN.
Future<List<Book>> searchBooks({required String query}) =>
    RustLib.instance.api.crateApiBookApiSearchBooks(query: query);

/// Updates the metadata and availability status of a book.
Future<void> updateBook({required Book book}) =>
    RustLib.instance.api.crateApiBookApiUpdateBook(book: book);

/// Removes a book from the system using its unique identifier.
Future<void> deleteBook({required String id}) =>
    RustLib.instance.api.crateApiBookApiDeleteBook(id: id);
