// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/borrowing.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initiates a borrow request for a book by a student.
Future<void> borrowBook({
  required String userId,
  required String userName,
  required String bookId,
}) => RustLib.instance.api.crateApiBorrowingApiBorrowBook(
  userId: userId,
  userName: userName,
  bookId: bookId,
);

/// Finalizes the return of a borrowed book.
Future<void> returnBook({required String borrowingId}) => RustLib.instance.api
    .crateApiBorrowingApiReturnBook(borrowingId: borrowingId);

/// Fetches all borrowing records for a specific user.
Future<List<Borrowing>> getUserBorrowings({required String userId}) =>
    RustLib.instance.api.crateApiBorrowingApiGetUserBorrowings(userId: userId);

/// Retrieves all borrowing records in the system.
Future<List<Borrowing>> getAllBorrowings() =>
    RustLib.instance.api.crateApiBorrowingApiGetAllBorrowings();

/// Lists all borrowings that are currently awaiting librarian approval.
Future<List<Borrowing>> getPendingBorrowings() =>
    RustLib.instance.api.crateApiBorrowingApiGetPendingBorrowings();

/// Approves a pending borrow request.
Future<void> approveBorrowing({
  required String borrowingId,
  required String dueDate,
}) => RustLib.instance.api.crateApiBorrowingApiApproveBorrowing(
  borrowingId: borrowingId,
  dueDate: dueDate,
);

/// Rejects a pending borrow request.
Future<void> rejectBorrowing({required String borrowingId}) => RustLib
    .instance
    .api
    .crateApiBorrowingApiRejectBorrowing(borrowingId: borrowingId);

/// Sends a return reminder notification to a student.
Future<void> sendReminder({required String borrowingId}) => RustLib.instance.api
    .crateApiBorrowingApiSendReminder(borrowingId: borrowingId);
