// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/penalty.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Penalty>> getUserPenalties({required String userId}) =>
    RustLib.instance.api.crateApiPenaltyApiGetUserPenalties(userId: userId);

Future<List<Penalty>> getAllPenalties() =>
    RustLib.instance.api.crateApiPenaltyApiGetAllPenalties();

Future<void> payPenalty({required String penaltyId}) =>
    RustLib.instance.api.crateApiPenaltyApiPayPenalty(penaltyId: penaltyId);
